# Datos de acceso a PostgreSQL
# spring.datasource.url=jdbc:postgresql://localhost:5432/centromedico
spring.datasource.url=jdbc:postgresql://172.25.1.98:5432/centromedico
spring.datasource.username=dev
spring.datasource.password=Jupiter2022*
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraci\u00f3n del Pool (Hikari)
# No necesitas crear la clase, Spring ya sabe usar estas l\u00edneas:
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000

# Evita que las p\u00e1ginas HTML se queden pegadas con la versi\u00f3n vieja
spring.thymeleaf.cache=false

# Para ver qu\u00e9 consultas SQL se est\u00e1n ejecutando en la consola
logging.level.org.springframework.jdbc=debug
spring.security.user.name=admin
spring.security.user.password=$2a$10$8.UnVuG9HHgffUDAlk8q2OuVGkqEnLPzSSeXyOq.7rthTcxL.66AC

# Para ver Log
# logging.level.org.springframework.security=DEBUG
# logging.level.org.springframework.web=DEBUG
